name: "ğŸƒâ€â™‚ï¸ Example workflow"

on:
  workflow_dispatch:
  
jobs:
  render_template:
    name: "âœï¸ Render template example"
    runs-on: ubuntu-latest
    steps:
    - name: "â¬‡ï¸ Checkout"
      uses: actions/checkout@v2.4.0
    
    - name: "âœï¸ Render Template"
      uses: yukitsune/template-cli@main
      with:
        args: --input ./example/example.txt \
          --value "person.name=Jason" \
          --value "person.age=25" \
          --value "message=Hello World!" \
          --output .
    
    - name: Print Template
      run: cat ./example.txt
